import type { Metadata } from "next";
import { EB_Garamond, Inter } from "next/font/google";
import "./_styles/globals.scss";
import "./_lib/actions";

const garamond = EB_Garamond({
  subsets: ["latin"],
  variable: "--font-garamond",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Leaderboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${garamond.variable}`}>
        {children}
      </body>
    </html>
  );
}
